### ISSUE TITLE
Getting the output of the toolbox

### ISSUE THREAD

**Issue by eugenekop** [TesterTi/LIDCToolbox#1]
First of all thank you very much for creating this toolbox. It should save me and others a lot of time!
I was wondering if it is possible to get the output of matched nodules created by the toolbox. Maybe the output is already sufficient and I won't actually need to run the code.

Thank you.

**Comment by TesterTi** [comment]
You're welcome.

The output would be very large for the whole dataset so I'm not sure how it could be sent (plus I do not have a local copy stored).

Are you not able to run the toolbox on your machine?

**Comment by zysno1** [comment]
Hi, TesterTi

I am a newbie about LIDC. I am learning about these now. Can you push a little dataset (less than five  dir ?) to github for newbie demo ? 

Thanks!

**Comment by TesterTi** [comment]
Good idea. I will do on Monday when I'm back in the office.

**Comment by zysno1** [comment]
Thanks, waiting for you:)

**Comment by TesterTi** [comment]
I've just updated the toolbox to include some sample outputs. These should help you to validate your installation (please see the readme's validation section for more information).
