### ISSUE TITLE
when i run it,i got some error

### ISSUE THREAD

**Issue by isihkr** [TesterTi/LIDCToolbox#11]
Hello! I try to run it on matlab2018b, but i got some error:

错误使用 LIDC_xml_2_pmap (line 143)
There was a problem executing Max (perhaps the slice spacing or something more serious -- see Max output
above). The studyID was 280315210397549164238230581781 and the input file was
F:\LIDC\input\LIDC-IDRI-0007\01-01-2000-81781\3000631-57680\1\081_1.xmltemp

出错 LIDC_process_annotations (line 234)
                LIDC_xml_2_pmap(new_xml_paths{i}{j}, new_xml_filenames{j}, pixel_spacing,
                slice_thickness, [xml_path, filename], studyID);

Could u pls help me fix it ?

**Comment by isihkr** [comment]
@TesterTi

**Comment by TesterTi** [comment]
Hi, I need more of the output to understand what went wrong. Can you attach a text file with the output before the link that you have sent (i.e. MAX's output)?

**Comment by TesterTi** [comment]
also, I have just pushed an update to the code, can you try the new version?

**Comment by isihkr** [comment]
Thanks for your reply！
I reinstalled Perl and the bug gone

**Comment by mehdializade** [comment]
Hello,I have use matlab2017b,win10/64bit,
and i have same error.
"""
Error using LIDC_xml_2_pmap (line 143)
There was a problem executing Max (perhaps the slice spacing or something more serious -- see Max output
above). The studyID was 660741147026674947967595590708 and the input file was
D:\Dr_foroozan\data\data\input\1\000_1.xmltemp

Error in LIDC_process_annotations (line 234)
                LIDC_xml_2_pmap(new_xml_paths{i}{j}, new_xml_filenames{j}, pixel_spacing,
                slice_thickness, [xml_path, filename], studyID);
"""
please help me to run it ...

**Comment by TesterTi** [comment]
Hi Mehdi,

I can't really do much without the full trace from Max (before the error that you quoted. The error that you have described just means that there was a problem executing Max but that could be due to many reasons (including a bad install of the required software).

**Comment by mehdializade** [comment]
I realized that I did not have "Max" in my pc. (not installed)
then i downloaded from github this and have a problem to install properly.
and i have installed activeperl.
I am confused.

**Comment by mehdializade** [comment]
Thank you for your reply.
My problem is this:

Messages produced during the run: 
  INFO[3109] (): Executing max.pl version 1.07b (2013-03-27 18:00:00 GMT).   
 
 INFO[3110] (): Executing on host DESKTOP-QG42KRL on  from directory D:/pezeshki/payan_name/code/lidc/matlab/LIDCToolbox-master  

  INFO[3201] (): The command line: D:\pezeshki\payan_name\code\lidc\matlab\LIDCToolbox-master\support_software\max-V107b\max-V107b.pl --skip-num-files-check --pixel-dim=0.703125 --slice-spacing=2.500000 --files=D:\Dr_foroozan\data\data\input\1\069_1.xmltemp --dir-out=D:\Dr_foroozan\data\data\input\1\max"   
  

FATAL[6307] (in MAX near line 2383): Error in opening the matching XML file (or its directory) for writing D:\Dr_foroozan\data\data\input\1\max"/matching.xml: Invalid argument  


  INFO[3101] (): Exit from max.pl with return code 121 (xmloutfileerror) at .

**Comment by TesterTi** [comment]
It appears that there is a problem with the command used to execute Max in Windows, this occurs in the file LIDC_xml_2_pmap.m

I don't have a windows machine to test this on but you should be able to easily correct the command, you just need to trace it back to where this extra " is being added. You can see that Max is trying to write to the directory:
D:\Dr_foroozan\data\data\input\1\max"/matching.xml
which obviously isn't correct. This must originate from line 130 or 144. It should be simple enough to correct.

Please also post back here the solution so that I can integrate it into the toolbox.

**Comment by mehdializade** [comment]
Thank You.
My problem solved.
In Windows new folder names are not saved with ".
And I had not used the "LIDC_xml_2_pmap.m" function with Windows support.
For Windows on line 127 it should be as follows:

if strcmpi(computer, 'MACI64') || strcmpi(computer, 'GLNXA64')
    cmd_str = ['perl "' MAX_path sprintf('max-V107b.pl" --skip-num-files-check --pixel-dim=%f --slice-spacing=%f --files=''%s'' --dir-out=''%s''', pixel_spacing, slice_spacing, [xml_path xml_filename], [xml_path 'max' filesep])];
else
    cmd_str = ['perl "' MAX_path sprintf('max-V107b.pl" --skip-num-files-check --pixel-dim=%f --slice-spacing=%f --files=%s --dir-out=%s', pixel_spacing, slice_spacing, [xml_path xml_filename], [xml_path 'max' filesep])];
end
