### ISSUE TITLE
Undefined function or variable 'imload'.

### ISSUE THREAD

**Issue by zysno1** [TesterTi/LIDCToolbox#3]
When I validate the environment, error has occured. Error message is: Undefined function or variable 'imload'.

My matlab version is R2016. Thanks.

**Comment by TesterTi** [comment]
Sorry that was a mistake in the readme, it should be imread: http://uk.mathworks.com/help/matlab/ref/imread.html

**Comment by zysno1** [comment]
Thanks，It's ok now.

I have two question. :)

1，Could you pull the original dicom image file and Radiologist Annotations/Segmentations to github which about your sample_output ? I want to check the differences between original dicom and tiff images. I can't download the dicom files from the NCI website.

2，I open the tiff image in the sample_output directory via matlab，I can't find the markup on the tiff image. Is the highlight zone ? What's the markup ?

Thank you for your help again!

**Comment by TesterTi** [comment]
Hi,
1. I cannot add the original DICOM images as they are over 300MB. I have instead added a set of instructions for downloading the exact data used to create the sample_output directory (see /sample_output/README.md).
2. The images (in the "images" directory) do no contain the markup, the images in the "gts" directory contain the markup. For example, the annotations for /sample_output/images/190188259083742759886805142125/slice4.tif are contained in /sample_output/gts/190188259083742759886805142125/slice4/
