### ISSUE TITLE
What is the definition of  "gts", "images", "masks" ?

### ISSUE THREAD

**Issue by zysno1** [TesterTi/LIDCToolbox#4]
Hi, TesterTi

```
  Thanks for your help.

  I don't know the definition of  these three direcotrys (gts, images, masks)。

  1，What is the difference between it ?  
  2，Do I view them through the same method(matlab, imagesc())?
  3，Which directory should I play If I want to make a presentation to other people for medicine demo ? 
```

**Comment by TesterTi** [comment]
1. The 'gts' directory contains the annotations for each slice converted from XML to image format, the 'images' directory contains images of the slices converted from DICOM, and the 'masks' directory contains masks which dictate which parts of the image that are in the scan (pixels containing 1 means that they are within the scan area, and 0 means that they are outside the scan area so should be ignored). See the readme for more information.
2. Yes all the images can be viewed using the same method.
3. I am not sure what your exact application is but I imagine that the 'images' and 'gts' directories are most important in your case. That way you can see the image captured during the scan, and the locations that the annotators marked as tumours.
