### ISSUE TITLE
How can I find the information about "characteristics" in xml file?

### ISSUE THREAD

**Issue by zysno1** [TesterTi/LIDCToolbox#5]
Hi, TesterTi

```
  I am studying the annotation xml about LIDC-IDRI-0002 now. There is a section which named "characteristics" in xml, But I can not found the description about it. 
  For exmple:
  <quote>

    <characteristics>
    <confidence>3</confidence>
    <subtlety>4</subtlety>
    <obscuration>2</obscuration>
    <reason>1</reason>
  </characteristics>  

  </quote>

  What is the meaning of "confidence" and "reason" ? Where can I found these description?

  I have search them at "https://cdebrowser.nci.nih.gov/CDEBrowser/", but nothing be found. 

 Thanks for your help!:)
```

**Comment by TesterTi** [comment]
I cannot give too much help on the actual dataset as I was not involved in creating it, but these are additional information related to the markings that the annotators have given. The definitions can be found in the following document: https://wiki.cancerimagingarchive.net/download/attachments/3539039/LIDC_XML_Documentation_1_Jan_2009.doc?version=1&modificationDate=1319224566057&api=v2

"Finally, each reader was asked to subjectively assess several characteristics of the nodule (each characteristic on a 1-5 scale):
    o   Subtlety – in terms of its difficulty in detection
    o   Internal structure – or expected internal composition of the nodule (soft tissue, fluid, fat, air)
    o   Calcificiation – pattern of calcification if present
    o   Sphericity – the three dimensional shape of the nodule in terms of its roundness:
    o   Margin – description of how well defined the margins of the nodule is.
    o   Spiculation – amount of speculation present in nodule
    o   Texture – internal texture or composition of nodule in terms of solid and ground glass components
    o   Malignancy - Radiologist subjective assessment of likelihood of malignancy of this nodule, ASSUMING  60-year-old male smoker"
